name: chatgpt_view
description: "ChatGPT View by June"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/chatgpt_view

version: 1.0.7

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:

dev_dependencies:
  basic_keyboard:
  bot_toast_module:
  chatgpt_appbar_view:
  chatgpt_drawer_view:
  config_theme:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view: #@add
  june_view_more:  #@add
  screenutil_module:
  theme_mode_changer: #@add

flutter:
  assets:
    - assets/view/chatgpt_view/
  uses-material-design: true